const { withClient } = require('./db');

const TXN_TABLES = ['shared_transactions', 'personal_transactions', 'offset_transactions'];

/** Ensure has_split / split_from_id exist on all transaction tables. */
async function ensureSplitColumns(client) {
  const { rows } = await client.query(
    `SELECT table_name, column_name
       FROM information_schema.columns
      WHERE table_name = ANY($1)
        AND column_name IN ('has_split', 'split_from_id')`,
    [TXN_TABLES],
  );
  const have = new Set(rows.map((r) => `${r.table_name}.${r.column_name}`));

  for (const table of TXN_TABLES) {
    if (!have.has(`${table}.has_split`)) {
      await client.query(`ALTER TABLE ${table} ADD COLUMN has_split BOOLEAN DEFAULT FALSE`);
      console.log(`Added has_split column to ${table}`);
    }
    if (!have.has(`${table}.split_from_id`)) {
      await client.query(
        `ALTER TABLE ${table} ADD COLUMN split_from_id INTEGER REFERENCES ${table}(id) ON DELETE SET NULL`,
      );
      console.log(`Added split_from_id column to ${table}`);
    }
  }
}

async function ensurePersonalSplitTables(client) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS personal_split_groups (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id VARCHAR(255) NOT NULL,
      group_name VARCHAR(255) NOT NULL,
      personal_category VARCHAR(255) NOT NULL,
      display_order INTEGER DEFAULT 0,
      is_active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, group_name)
    )`);
  await client.query(`
    CREATE TABLE IF NOT EXISTS personal_split_mapping (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id VARCHAR(255) NOT NULL,
      personal_split_group_id INTEGER NOT NULL,
      budget_category VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, personal_split_group_id, budget_category),
      FOREIGN KEY (personal_split_group_id) REFERENCES personal_split_groups(id) ON DELETE CASCADE
    )`);
  console.log('✅ Personal split tables ensured');
}

async function ensureBudgetCategories(client) {
  const { rows } = await client.query('SELECT COUNT(*)::int AS count FROM budget_category');
  if (rows[0].count > 0) {
    console.log(`✅ Budget category table already has ${rows[0].count} categories`);
    return;
  }
  const defaults = [
    ['Vehicle', 100], ['Entertainment', 100], ['Food', 500], ['Home', 100],
    ['Medical', 50], ['Personal Items', 120], ['Travel', 50], ['Other', 100],
    ['Mortgage', 2500], ['Bills', 1000], ['Savings', 1000], ['Gifts', 150], ['Holidays', 300],
  ];
  await client.query(
    `INSERT INTO budget_category (category, budget)
     SELECT * FROM UNNEST($1::text[], $2::numeric[])
     ON CONFLICT (category) DO NOTHING`,
    [defaults.map((d) => d[0]), defaults.map((d) => d[1])],
  );
  console.log(`✅ Populated budget_category table with ${defaults.length} default categories`);
}

async function runMigrations() {
  try {
    await withClient(async (client) => {
      await ensureSplitColumns(client);
      await ensurePersonalSplitTables(client);
      await ensureBudgetCategories(client);
    });
  } catch (err) {
    console.error('❌ Error running startup migrations:', err);
  }
}

module.exports = { runMigrations };
